name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --without docs

      - name: Run tests
        run: poetry run pytest --cov --cov-branch --cov-report=xml

      - name: Add coverage to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
